# Generated by Django 3.1 on 2020-08-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200809_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_answer',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_first_screen',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_partners',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_questions',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_reviews',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_second_scree',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_step_work',
        ),
        migrations.AddField(
            model_name='homefirstscreen',
            name='home_first_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
        migrations.AddField(
            model_name='homepartners',
            name='home_partners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
        migrations.AddField(
            model_name='homequestions',
            name='home_questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
        migrations.AddField(
            model_name='homequestions',
            name='questions',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='homereviews',
            name='home_reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
        migrations.AddField(
            model_name='homesecondscreen',
            name='home_second_scree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
        migrations.AddField(
            model_name='homestepwork',
            name='home_step_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
        migrations.DeleteModel(
            name='HomeAnswer',
        ),
    ]
