# Generated by Django 3.1 on 2020-08-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200810_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homefirstscreen',
            options={'verbose_name': 'Первыйый скрин', 'verbose_name_plural': 'Первыйый скрин'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главную', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterModelOptions(
            name='homepartners',
            options={'verbose_name': 'Наши партнеры', 'verbose_name_plural': 'Наши партнеры'},
        ),
        migrations.AlterModelOptions(
            name='homequestions',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='homereviews',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='homesecondscreen',
            options={'verbose_name': 'Второй скрин', 'verbose_name_plural': 'Второй скрин'},
        ),
        migrations.AlterModelOptions(
            name='homestepwork',
            options={'verbose_name': 'Как мы работаем', 'verbose_name_plural': 'Как мы работаем'},
        ),
        migrations.AlterField(
            model_name='homefirstscreen',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фон офера'),
        ),
        migrations.AlterField(
            model_name='homepartners',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото партнера'),
        ),
        migrations.AlterField(
            model_name='homereviews',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка отзыва'),
        ),
    ]
