# Generated by Django 3.1 on 2020-08-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200810_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefirstscreen',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фон офера'),
        ),
        migrations.AlterField(
            model_name='homesecondscreen',
            name='description',
            field=models.TextField(verbose_name='описание компнании'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description',
            field=models.TextField(verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description2',
            field=models.TextField(verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description3',
            field=models.TextField(verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description4',
            field=models.TextField(verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description5',
            field=models.TextField(verbose_name='Описание шага'),
        ),
    ]
