# Generated by Django 3.1 on 2020-08-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200810_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestepwork',
            name='description6',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AddField(
            model_name='homestepwork',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка шага'),
        ),
        migrations.AddField(
            model_name='homestepwork',
            name='title6',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description2',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description3',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description4',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='description5',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='title2',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='title3',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='title4',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
        migrations.AlterField(
            model_name='homestepwork',
            name='title5',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
    ]
