# Generated by Django 3.1 on 2020-08-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200810_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('money', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('post', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото слайдера')),
                ('services_page', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='blog.servicespage')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('services_page', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='blog.servicespage')),
            ],
            options={
                'verbose_name': 'Выгода',
                'verbose_name_plural': 'Выгода',
            },
        ),
    ]
