# Generated by Django 3.1 on 2020-08-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_servicespage_servicespagebenefit_servicespageslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicespage',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='post',
        ),
    ]
