# Generated by Django 3.1 on 2020-08-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200811_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='post',
            field=models.TextField(blank=True),
        ),
    ]
