# Generated by Django 3.1 on 2020-08-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_servicespage_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicespage',
            old_name='post',
            new_name='content',
        ),
    ]
