# Generated by Django 3.1 on 2020-08-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200811_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('description', models.CharField(max_length=255)),
                ('home_icon', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Иконка главная')),
                ('services_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Иконка услуг')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='servicespage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services_page', to='blog.servicescategory'),
        ),
    ]
