# Generated by Django 3.1 on 2020-08-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200811_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicescategory',
            old_name='home_icon',
            new_name='services_icon',
        ),
    ]
