# Generated by Django 3.1 on 2020-08-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200811_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescategory',
            name='services_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
    ]
