# Generated by Django 3.1 on 2020-08-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_servicescategory_services_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicescategory',
            name='services_category',
        ),
    ]
