# Generated by Django 3.1 on 2020-08-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_servicescategory_services_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescategory',
            name='home_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
    ]
