# Generated by Django 3.1 on 2020-08-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_servicescategory_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicescategory',
            name='home_page',
        ),
    ]
