# Generated by Django 3.1 on 2020-08-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_servicescategory_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescategory',
            name='home_services_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.homepage'),
        ),
    ]
