# Generated by Django 3.1 on 2020-08-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_servicescategory_home_services_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicescategory',
            old_name='slug',
            new_name='slug_category',
        ),
    ]
