# Generated by Django 3.1 on 2020-08-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200811_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='photo_services',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото на категорию'),
        ),
    ]
