# Generated by Django 3.1 on 2020-08-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_servicespage_photo_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='description_services',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание на категорию'),
        ),
    ]
