# Generated by Django 3.1 on 2020-08-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_servicespage_description_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicescategory',
            old_name='slug_category',
            new_name='slug',
        ),
    ]
