# Generated by Django 3.1 on 2020-08-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200811_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeysPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('content', models.TextField(blank=True)),
                ('category', models.ManyToManyField(to='blog.ServicesCategory')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейс',
            },
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='category',
        ),
        migrations.AddField(
            model_name='servicespage',
            name='category',
            field=models.ManyToManyField(to='blog.ServicesCategory'),
        ),
        migrations.CreateModel(
            name='KeysPageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото слайдера')),
                ('keys_page', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='blog.keyspage')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдр',
            },
        ),
    ]
