# Generated by Django 3.1 on 2020-08-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200813_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyspage',
            old_name='photo_home',
            new_name='photo_keys_home',
        ),
    ]
